export interface TutorialStep {
  id: string;
  title: string;
  description: string;
  duration?: number;
  target?: string;
  placement?: 'top' | 'bottom' | 'left' | 'right';
}

export const merchantTutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Merchant Dashboard! 🎉',
    description: 'This quick tour will show you how to manage your content, view contracts, and grow your creative business on PIE.',
    duration: 12000,
  },
  {
    id: 'approval-status',
    title: 'Your Approval Status',
    description: 'Check your merchant approval status here. Once approved, you can upload and sell content to supporters.',
    duration: 10000,
    target: '[data-tutorial="approval-status"]',
    placement: 'bottom',
  },
  {
    id: 'account-setup',
    title: 'Account Setup',
    description: 'Complete your profile and add payment information to start receiving earnings from your content sales.',
    duration: 10000,
    target: '[data-tutorial="account-setup"]',
    placement: 'right',
  },
  {
    id: 'astrology-products',
    title: 'Astrology Products',
    description: 'Browse and purchase astrology readings. These products are managed by administrators.',
    duration: 10000,
    target: '[data-tutorial="astrology-products"]',
    placement: 'right',
  },
  {
    id: 'fashion-products',
    title: 'Fashion Products',
    description: 'Explore fashion items available for purchase. You can also apply to model products you\'ve purchased.',
    duration: 10000,
    target: '[data-tutorial="fashion-products"]',
    placement: 'left',
  },
  {
    id: 'audio-products',
    title: 'Audio Products & Music',
    description: 'Upload and manage your music tracks, podcasts, and ASMR content. Set pricing and availability for each item.',
    duration: 10000,
    target: '[data-tutorial="audio-products"]',
    placement: 'bottom',
  },
  {
    id: 'modeling',
    title: 'Modeling Applications',
    description: 'Apply to model fashion products you\'ve purchased. Submit photos and wait for admin approval.',
    duration: 10000,
    target: '[data-tutorial="modeling"]',
    placement: 'bottom',
  },
  {
    id: 'playlist-settings',
    title: 'Playlist Settings',
    description: 'Control whether your playlist is publicly visible on your profile page.',
    duration: 10000,
    target: '[data-tutorial="playlist-settings"]',
    placement: 'top',
  },
  {
    id: 'media-players',
    title: 'Your Media Library',
    description: 'Access all your purchased music, podcasts, and videos in one place. Your personal media collection.',
    duration: 10000,
    target: '[data-tutorial="media-players"]',
    placement: 'top',
  },
];

export const supporterTutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to PIE! 🎉',
    description: 'Your supporter dashboard is your hub for discovering content, managing purchases, and supporting creators.',
    duration: 12000,
  },
  {
    id: 'tax-calculator',
    title: 'Tax Planning (If Applicable)',
    description: 'If you earn referral income, use the Self-Employment Tax Calculator to estimate your quarterly taxes.',
    duration: 10000,
    target: '[data-tutorial="tax-calculator"]',
    placement: 'bottom',
  },
  {
    id: 'music-tab',
    title: 'Music & Podcasts',
    description: 'Listen to all your purchased music tracks and podcast episodes. Your library grows as you support creators.',
    duration: 10000,
    target: '[data-tutorial="music-tab"]',
    placement: 'bottom',
  },
  {
    id: 'videos-tab',
    title: 'Videos',
    description: 'Watch your purchased video content. All your video purchases are saved here for easy access.',
    duration: 10000,
    target: '[data-tutorial="videos-tab"]',
    placement: 'bottom',
  },
  {
    id: 'gallery-tab',
    title: 'Content Gallery',
    description: 'Upload and manage your personal photos and videos. Share your creative content with the community.',
    duration: 10000,
    target: '[data-tutorial="gallery-tab"]',
    placement: 'bottom',
  },
  {
    id: 'profile-tab',
    title: 'Your Profile',
    description: 'Manage your profile settings, view your portfolios, and control your playlist visibility.',
    duration: 10000,
    target: '[data-tutorial="profile-tab"]',
    placement: 'bottom',
  },
  {
    id: 'background-tab',
    title: 'Background Customization',
    description: 'Upload a custom background image or video to personalize your dashboard experience.',
    duration: 10000,
    target: '[data-tutorial="background-tab"]',
    placement: 'bottom',
  },
  {
    id: 'playlist-public',
    title: 'Playlist Visibility',
    description: 'Toggle whether your playlist is publicly visible to other users. Control your privacy settings here.',
    duration: 10000,
    target: '[data-tutorial="playlist-public"]',
    placement: 'top',
  },
];

export const musicArtistTutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Your Music Artist Dashboard! 🎵',
    description: 'This quick tour will show you how to upload music, manage your tracks, and grow your audience on PIE.',
    duration: 12000,
  },
  {
    id: 'music-upload',
    title: 'Upload Your Music',
    description: 'Upload and manage your music tracks here. Set pricing, add album art, and publish to the store.',
    duration: 10000,
    target: '[data-tutorial="music-upload"]',
    placement: 'bottom',
  },
  {
    id: 'music-tab',
    title: 'Your Music Library',
    description: 'Listen to music and podcasts you\'ve purchased from other artists. Your personal media collection.',
    duration: 10000,
    target: '[data-tutorial="music-tab"]',
    placement: 'bottom',
  },
  {
    id: 'gallery-tab',
    title: 'Content Gallery',
    description: 'Upload photos and videos to showcase your creative journey. Share behind-the-scenes content.',
    duration: 10000,
    target: '[data-tutorial="gallery-tab"]',
    placement: 'bottom',
  },
  {
    id: 'background-tab',
    title: 'Customize Your Dashboard',
    description: 'Upload a custom background to personalize your dashboard experience.',
    duration: 10000,
    target: '[data-tutorial="background-tab"]',
    placement: 'bottom',
  },
  {
    id: 'playlist-public',
    title: 'Playlist Visibility',
    description: 'Control whether your playlist is publicly visible on your profile page.',
    duration: 10000,
    target: '[data-tutorial="playlist-public"]',
    placement: 'top',
  },
];

export const adminTutorialSteps: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Admin Dashboard Overview 👑',
    description: 'Welcome to the admin panel. Manage merchants, review submissions, and oversee platform operations.',
    duration: 12000,
  },
  {
    id: 'tax-calculator',
    title: 'Tax Planning Tools',
    description: 'Access the Self-Employment Tax Calculator for your own tax planning as needed.',
    duration: 10000,
    target: '[data-tutorial="tax-calculator"]',
    placement: 'bottom',
  },
  {
    id: 'merchants-tab',
    title: 'Merchant Management',
    description: 'Review and approve merchant applications. Manage merchant status and permissions.',
    duration: 10000,
    target: '[data-tutorial="merchants-tab"]',
    placement: 'bottom',
  },
  {
    id: 'submissions-tab',
    title: 'Contract Submissions',
    description: 'Review cover submissions, modeling applications, ASMR downloads, and video ad submissions from merchants.',
    duration: 10000,
    target: '[data-tutorial="submissions-tab"]',
    placement: 'bottom',
  },
  {
    id: 'reviews-tab',
    title: 'Product Reviews',
    description: 'Moderate and manage product reviews submitted by users across all product categories.',
    duration: 10000,
    target: '[data-tutorial="reviews-tab"]',
    placement: 'bottom',
  },
  {
    id: 'gallery-tab',
    title: 'Content Gallery',
    description: 'View and manage all user-uploaded content. Monitor for policy compliance.',
    duration: 10000,
    target: '[data-tutorial="gallery-tab"]',
    placement: 'bottom',
  },
  {
    id: 'bulletin-tab',
    title: 'Bulletin Posts',
    description: 'Manage bulletin board posts, announcements, and TV Guide entries created by merchants.',
    duration: 10000,
    target: '[data-tutorial="bulletin-tab"]',
    placement: 'bottom',
  },
  {
    id: 'video-ads',
    title: 'Video Ad Opportunities',
    description: 'Create and manage video ad opportunities for merchants to apply to and submit content for.',
    duration: 10000,
    target: '[data-tutorial="video-ads"]',
    placement: 'top',
  },
];
